# Generated by Django 3.1.5 on 2021-01-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210107_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(default='Python', max_length=100),
        ),
    ]
